// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: admin.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Admin_AdminLoginRequest_FullMethodName    = "/pb.Admin/AdminLoginRequest"
	Admin_AdminAddCategory_FullMethodName     = "/pb.Admin/AdminAddCategory"
	Admin_AdminViewPackages_FullMethodName    = "/pb.Admin/AdminViewPackages"
	Admin_AdminViewpackage_FullMethodName     = "/pb.Admin/AdminViewpackage"
	Admin_AdminPacakgeStatus_FullMethodName   = "/pb.Admin/AdminPacakgeStatus"
	Admin_AdminViewCategories_FullMethodName  = "/pb.Admin/AdminViewCategories"
	Admin_AdminViewDestination_FullMethodName = "/pb.Admin/AdminViewDestination"
	Admin_AdminViewActivity_FullMethodName    = "/pb.Admin/AdminViewActivity"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	AdminLoginRequest(ctx context.Context, in *AdminLogin, opts ...grpc.CallOption) (*AdminResponce, error)
	AdminAddCategory(ctx context.Context, in *AdminCategory, opts ...grpc.CallOption) (*AdminResponce, error)
	AdminViewPackages(ctx context.Context, in *AdminView, opts ...grpc.CallOption) (*AdminPackages, error)
	AdminViewpackage(ctx context.Context, in *AdminView, opts ...grpc.CallOption) (*AdminPackage, error)
	AdminPacakgeStatus(ctx context.Context, in *AdminView, opts ...grpc.CallOption) (*AdminResponce, error)
	AdminViewCategories(ctx context.Context, in *AdminView, opts ...grpc.CallOption) (*AdminCatagories, error)
	AdminViewDestination(ctx context.Context, in *AdminView, opts ...grpc.CallOption) (*AdminDestination, error)
	AdminViewActivity(ctx context.Context, in *AdminView, opts ...grpc.CallOption) (*AdminActivity, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) AdminLoginRequest(ctx context.Context, in *AdminLogin, opts ...grpc.CallOption) (*AdminResponce, error) {
	out := new(AdminResponce)
	err := c.cc.Invoke(ctx, Admin_AdminLoginRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AdminAddCategory(ctx context.Context, in *AdminCategory, opts ...grpc.CallOption) (*AdminResponce, error) {
	out := new(AdminResponce)
	err := c.cc.Invoke(ctx, Admin_AdminAddCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AdminViewPackages(ctx context.Context, in *AdminView, opts ...grpc.CallOption) (*AdminPackages, error) {
	out := new(AdminPackages)
	err := c.cc.Invoke(ctx, Admin_AdminViewPackages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AdminViewpackage(ctx context.Context, in *AdminView, opts ...grpc.CallOption) (*AdminPackage, error) {
	out := new(AdminPackage)
	err := c.cc.Invoke(ctx, Admin_AdminViewpackage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AdminPacakgeStatus(ctx context.Context, in *AdminView, opts ...grpc.CallOption) (*AdminResponce, error) {
	out := new(AdminResponce)
	err := c.cc.Invoke(ctx, Admin_AdminPacakgeStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AdminViewCategories(ctx context.Context, in *AdminView, opts ...grpc.CallOption) (*AdminCatagories, error) {
	out := new(AdminCatagories)
	err := c.cc.Invoke(ctx, Admin_AdminViewCategories_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AdminViewDestination(ctx context.Context, in *AdminView, opts ...grpc.CallOption) (*AdminDestination, error) {
	out := new(AdminDestination)
	err := c.cc.Invoke(ctx, Admin_AdminViewDestination_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AdminViewActivity(ctx context.Context, in *AdminView, opts ...grpc.CallOption) (*AdminActivity, error) {
	out := new(AdminActivity)
	err := c.cc.Invoke(ctx, Admin_AdminViewActivity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility
type AdminServer interface {
	AdminLoginRequest(context.Context, *AdminLogin) (*AdminResponce, error)
	AdminAddCategory(context.Context, *AdminCategory) (*AdminResponce, error)
	AdminViewPackages(context.Context, *AdminView) (*AdminPackages, error)
	AdminViewpackage(context.Context, *AdminView) (*AdminPackage, error)
	AdminPacakgeStatus(context.Context, *AdminView) (*AdminResponce, error)
	AdminViewCategories(context.Context, *AdminView) (*AdminCatagories, error)
	AdminViewDestination(context.Context, *AdminView) (*AdminDestination, error)
	AdminViewActivity(context.Context, *AdminView) (*AdminActivity, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (UnimplementedAdminServer) AdminLoginRequest(context.Context, *AdminLogin) (*AdminResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminLoginRequest not implemented")
}
func (UnimplementedAdminServer) AdminAddCategory(context.Context, *AdminCategory) (*AdminResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminAddCategory not implemented")
}
func (UnimplementedAdminServer) AdminViewPackages(context.Context, *AdminView) (*AdminPackages, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminViewPackages not implemented")
}
func (UnimplementedAdminServer) AdminViewpackage(context.Context, *AdminView) (*AdminPackage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminViewpackage not implemented")
}
func (UnimplementedAdminServer) AdminPacakgeStatus(context.Context, *AdminView) (*AdminResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminPacakgeStatus not implemented")
}
func (UnimplementedAdminServer) AdminViewCategories(context.Context, *AdminView) (*AdminCatagories, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminViewCategories not implemented")
}
func (UnimplementedAdminServer) AdminViewDestination(context.Context, *AdminView) (*AdminDestination, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminViewDestination not implemented")
}
func (UnimplementedAdminServer) AdminViewActivity(context.Context, *AdminView) (*AdminActivity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminViewActivity not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_AdminLoginRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminLogin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminLoginRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminLoginRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminLoginRequest(ctx, req.(*AdminLogin))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AdminAddCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminCategory)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminAddCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminAddCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminAddCategory(ctx, req.(*AdminCategory))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AdminViewPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminView)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminViewPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminViewPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminViewPackages(ctx, req.(*AdminView))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AdminViewpackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminView)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminViewpackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminViewpackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminViewpackage(ctx, req.(*AdminView))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AdminPacakgeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminView)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminPacakgeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminPacakgeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminPacakgeStatus(ctx, req.(*AdminView))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AdminViewCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminView)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminViewCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminViewCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminViewCategories(ctx, req.(*AdminView))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AdminViewDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminView)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminViewDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminViewDestination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminViewDestination(ctx, req.(*AdminView))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AdminViewActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminView)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminViewActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminViewActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminViewActivity(ctx, req.(*AdminView))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminLoginRequest",
			Handler:    _Admin_AdminLoginRequest_Handler,
		},
		{
			MethodName: "AdminAddCategory",
			Handler:    _Admin_AdminAddCategory_Handler,
		},
		{
			MethodName: "AdminViewPackages",
			Handler:    _Admin_AdminViewPackages_Handler,
		},
		{
			MethodName: "AdminViewpackage",
			Handler:    _Admin_AdminViewpackage_Handler,
		},
		{
			MethodName: "AdminPacakgeStatus",
			Handler:    _Admin_AdminPacakgeStatus_Handler,
		},
		{
			MethodName: "AdminViewCategories",
			Handler:    _Admin_AdminViewCategories_Handler,
		},
		{
			MethodName: "AdminViewDestination",
			Handler:    _Admin_AdminViewDestination_Handler,
		},
		{
			MethodName: "AdminViewActivity",
			Handler:    _Admin_AdminViewActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
